SmartGhrWali/urls.py
from django.urls import path
from . import views

app_name = 'SmartGhrWali'
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("purchases/", views.purchases, name="purchases"),
    path("purchases/<int:purchase_id>/delete/", views.delete_purchase, name="delete_purchase"),
    path("usages/", views.usages, name="usages"),
    path("usages/<int:usage_id>/delete/", views.delete_usage, name="delete_usage"),
    path("recipes/", views.recipe_page, name="recipe_page"),
    path("recipes/fetch_recipes/", views.fetch_recipes, name="fetch_recipes"),
    path("register/", views.register, name="register"),
    path("reports/inventory/", views.monthly_inventory_report, name='inventory_report'),
    path("reports/monthly-inventory/", views.report_download_page, name='monthly_inventory_report'),
]

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/homepage.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
        {% block title %}
        Smart Ghr Wali
        {% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="/SmartGhrWali/">
                <!-- <img src="/static/images/website_logo.png" alt="SMART GHAR WALI KITCHEN INVENTORY" style="height: 35px; width: 75px;;"> -->
                <h5 style="font-family:cursive; color: #f2fcf7;">Smart Ghr Wali</h5>
            </a>
            </div>
         
        <div class="container-fluid">
            <!-- <a class="navbar-brand" href="/SmartGhrWali/">Home</a> -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/SmartGhrWali/dashboard/' %}active{% endif %}"
                            href="{% url 'SmartGhrWali:dashboard' %}" aria-current="page">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/SmartGhrWali/purchases/' %}active{% endif %}"
                            href="{% url 'SmartGhrWali:purchases' %}">Purchases</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/SmartGhrWali/usages/' %}active{% endif %}"
                            href="{% url 'SmartGhrWali:usages' %}">Usages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/SmartGhrWali/reports/monthly-expense/' %}active{% endif %}"
                            href="{% url 'SmartGhrWali:monthly_inventory_report' %}">Reports</a>
                    </li>
                </ul>
                <!-- <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Log Out</a>
                </form>
                {% else %}
                <div class="button-group">
                    <a href="{% url 'SmartGhrWali:register' %}" class="btn btn-primary">Sign Up </a>
                    
                </div>
                {% endif %}
               
            </div>
        </div>
    </nav>
    <div class="w-100" style="margin-top: 1px;">
        {% block content %}
        {% endblock %}
    </div>
      <script src="/static/js/script.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>